# Generated by Django 3.2.8 on 2021-10-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='myapp')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
